version: 40
imports:
- projectPath: common/java/gradle-javafx
  revision: main
  accessTokenSecret: common-import
jobs:
- name: Push to Github
  steps:
  - !PushRepository
    name: Github
    remoteUrl: https://github.com/mnellemann/mdns-explorer.git
    userName: mnellemann
    passwordSecret: GITHUB-TOKEN
    force: false
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !ScheduleTrigger
    cronExpression: 0 0 0 * * ?
    projects: mark/mdns-explorer
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
