version: 40
imports:
- projectPath: common/java/gradle-javafx
  revision: main
jobs:
- name: Pull from Github
  steps:
  - !PullRepository
    name: Github
    remoteUrl: https://github.com/mnellemann/mdns-explorer.git
    refs: refs/head/* refs/tags/*
    withLfs: false
    force: false
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !ScheduleTrigger
    cronExpression: 0 0 0 * * ?
    projects: mark/mdns-explorer
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400

